name: Build And Deploy Non Libraries

on:
  push:    
    branches: 
      - 'release/nodependencies/**'
env:
  CONFIGURATION: 'Release'
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout.
        uses: actions/checkout@v3
      - name: Setup .NET.
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.404
      - name: Restore packages.
        run: dotnet restore
      - name: Build Solution
        run: dotnet build --configuration $CONFIGURATION --no-restore
      - name: Run unit tests.
        run: dotnet test --no-build --configuration $CONFIGURATION --no-restore --verbosity normal
      - name: Cleaning distribuition folder.
        run: rm -rf dist/*.nupkg
      - name: Pack DocumentNumber.PaymentCardNumber.Generator.Common
        run: dotnet pack --no-build --configuration $CONFIGURATION --no-restore --output ./dist/ ./src/DocumentNumber.PaymentCardNumber.Generator.Common/DocumentNumber.PaymentCardNumber.Generator.Common.csproj
      - name: Pack DocumentNumber.ValidatorAbstractions
        run: dotnet pack --no-build --configuration $CONFIGURATION --no-restore --output ./dist/ ./src/DocumentNumber.ValidatorAbstractions/DocumentNumber.ValidatorAbstractions.csproj
      - name: Pack DocumentNumber.Portugal.BankAccountNumber.Generator
        run: dotnet pack --no-build --configuration $CONFIGURATION --no-restore --output ./dist/ ./src/DocumentNumber.Portugal.BankAccountNumber.Generator/DocumentNumber.Portugal.BankAccountNumber.Generator.csproj
      - name: Pack DocumentNumber.Portugal.CitizenCard.Generator
        run: dotnet pack --no-build --configuration $CONFIGURATION --no-restore --output ./dist/ ./src/DocumentNumber.Portugal.CitizenCard.Generator/DocumentNumber.Portugal.CitizenCard.Generator.csproj
      - name: Pack DocumentNumber.Portugal.Nif.Generator
        run: dotnet pack --no-build --configuration $CONFIGURATION --no-restore --output ./dist/ ./src/DocumentNumber.Portugal.Nif.Generator/DocumentNumber.Portugal.Nif.Generator.csproj
      - name: Pack DocumentNumber.Portugal.Niss.Generator
        run: dotnet pack --no-build --configuration $CONFIGURATION --no-restore --output ./dist/ ./src/DocumentNumber.Portugal.Niss.Generator/DocumentNumber.Portugal.Niss.Generator.csproj
      - name: Upload nuget packages
        uses: actions/upload-artifact@v3.1.0
        with:
          path: './dist'
  publish_nuget_org:
    needs: build_and_test
    runs-on: ubuntu-latest
    environment:
      name: NUGET_ORG
      url: 'https://www.nuget.org/profiles/masterzdran'
    steps:
      - name: Download nuget packages
        uses: actions/download-artifact@v3.0.0
        with:
          path: './dist'
      - name: Publish nuget.org
        run: dotnet nuget push dist/artifact/*.nupkg --api-key ${{secrets.NUGET_ORG_TOKEN}} --source https://api.nuget.org/v3/index.json