name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build Document.Validator.sln --no-restore
    - name: Test
      run: dotnet test Document.Validator.sln /p:CollectCoverage=true /p:CoverletOutput=../../coverage/ /p:CoverletOutputFormat=opencover --no-build --verbosity normal
